name: his
channels:
  - conda-forge
dependencies:
  - python=3.7
  - django=2.1.5
  - djangorestframework=3.9.1
  - djangorestframework-xml=1.3.0
  - gunicorn=19.9.0
  - pip=18.1
  - pip:
    - drf-yasg==1.12.0
